libevent-dev is required
Without `libevent-dev`, the following error may occur:

```
gevent/libevent.h:9:19: fatal error: event.h: No such file or directory
```